/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class Juego extends javax.swing.JFrame {

   Verificación miVerificacion;
   int intentos;
    
    
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        letra1 = new javax.swing.JTextField();
        jugar = new javax.swing.JButton();
        letra2 = new javax.swing.JTextField();
        jugar2 = new javax.swing.JButton();
        letra3 = new javax.swing.JTextField();
        letra4 = new javax.swing.JTextField();
        letra5 = new javax.swing.JTextField();
        jugar3 = new javax.swing.JButton();
        jugar4 = new javax.swing.JButton();
        jugar5 = new javax.swing.JButton();
        nointentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        letra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra1ActionPerformed(evt);
            }
        });

        jugar.setText("Jugar");
        jugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugarMouseClicked(evt);
            }
        });

        jugar2.setText("Jugar");
        jugar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugar2MouseClicked(evt);
            }
        });

        jugar3.setText("Jugar");
        jugar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugar3MouseClicked(evt);
            }
        });

        jugar4.setText("Jugar");
        jugar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugar4MouseClicked(evt);
            }
        });

        jugar5.setText("Jugar");
        jugar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jugar5MouseClicked(evt);
            }
        });

        nointentos.setText("Número de Intentos");
        nointentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nointentosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jugar5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nointentos)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(letra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letra5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jugar)
                    .addComponent(jugar2)
                    .addComponent(jugar3)
                    .addComponent(jugar4)
                    .addComponent(jugar5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(nointentos)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_letra1ActionPerformed

    private void jugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugarMouseClicked

     if(letra1.getText().equals("a")){
    
         JOptionPane.showMessageDialog(null,"Bien");
        
     }else{
         JOptionPane.showMessageDialog(null,"No es la letra :v");
     }
      
     intentos++;

    }//GEN-LAST:event_jugarMouseClicked

    private void jugar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar2MouseClicked

    if(letra2.getText().equals("r")){
    
         JOptionPane.showMessageDialog(null,"Bien");
        
     }else{
         JOptionPane.showMessageDialog(null,"No es la letra :v");
     }
      
    intentos++;
        
    }//GEN-LAST:event_jugar2MouseClicked

    private void jugar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar3MouseClicked
       
    if(letra3.getText().equals("b")){
    
         JOptionPane.showMessageDialog(null,"Bien");
        
     }else{
         JOptionPane.showMessageDialog(null,"No es la letra :v");
     }        
    
    intentos++;
    
    }//GEN-LAST:event_jugar3MouseClicked

    private void jugar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar4MouseClicked
    
    if(letra4.getText().equals("o")){
    
         JOptionPane.showMessageDialog(null,"Bien");
        
     }else{
         JOptionPane.showMessageDialog(null,"No es la letra :v");
     }       
        intentos++;
    }//GEN-LAST:event_jugar4MouseClicked

    private void jugar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar5MouseClicked
    
    if(letra5.getText().equals("l")){
    
         JOptionPane.showMessageDialog(null,"Bien");
        
     }else{
         JOptionPane.showMessageDialog(null,"No es la letra :v");
     }        
    
    intentos++;
    }//GEN-LAST:event_jugar5MouseClicked

    private void nointentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nointentosMouseClicked
    
         JOptionPane.showMessageDialog(null, "Le tomo "+ intentos + " en solucionar el ahorcado. ");
        
    }//GEN-LAST:event_nointentosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jugar;
    private javax.swing.JButton jugar2;
    private javax.swing.JButton jugar3;
    private javax.swing.JButton jugar4;
    private javax.swing.JButton jugar5;
    private javax.swing.JTextField letra1;
    private javax.swing.JTextField letra2;
    private javax.swing.JTextField letra3;
    private javax.swing.JTextField letra4;
    private javax.swing.JTextField letra5;
    private javax.swing.JButton nointentos;
    // End of variables declaration//GEN-END:variables

    private void resultado(){
        
    
        
    }








}
